#!/bin/bash

_font=${_o[font]:-${GTK_ALT_FONT:-"Noto Sans 12"}}

main(){

  [[ $* ]] || ERX "missing COMMAND"

  xfsettings_is_running \
    || ERX "xfsettingsd is not running"

  xfconf_query_command_exist \
    || ERX "xfconf-query command not found"

  (
    current_font=$(get_gtk_font)
    set_gtk_font "$_font"
    sleep "${_o[sleep]:-3}"
    set_gtk_font "$current_font"
  ) &

  exec "$@"
}

xfsettings_is_running() {
  pidof xfsettingsd >/dev/null || return 1
}

xfconf_query_command_exist() {
  command -v xfconf-query > /dev/null || return 1
}

set_gtk_font() {

  xfconf-query --create                 \
               --channel xsettings      \
               --property /Gtk/FontName \
               --type string            \
               --set "$1"
}

get_gtk_font() {

  xfconf-query --create                 \
               --channel xsettings      \
               --property /Gtk/FontName
  
}

__dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")") #bashbud
source "$__dir/_init.sh"                              #bashbud
